[package]
name = "bluer-miflora"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bluer = { version = "0.17.3", features = ["bluetoothd"] }
env_logger = "0.11.5"
futures = "0.3.31"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
