[workspace]
members = ["./cli", "./lib"]
resolver = "2"

[workspace.package]
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/jdrouet/bluer-miflora/"
